# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTnP_hj8Hg9g-SBXSHBhe_vnkcGTh4HP
"""

from pathlib import Path
import pandas as pd
import plotly.express as px
import streamlit as st

# --------------------------------------------------
# Configuración de la página
# --------------------------------------------------
st.set_page_config(page_title="EDA Vehículos", layout="wide")
st.header("Análisis exploratorio de anuncios de vehículos")

# --------------------------------------------------
# Carga de datos (con cache)
# --------------------------------------------------
DATA_PATH = Path("vehicles_us.csv")

@st.cache_data
def load_data(path):
    return pd.read_csv(path, low_memory=False)

try:
    car_data = load_data(DATA_PATH)
    st.caption(
        f"Archivo cargado: `{DATA_PATH.name}` | "
        f"Filas: {len(car_data):,} | Columnas: {len(car_data.columns)}"
    )
except FileNotFoundError:
    st.error("No se encontró el archivo vehicles_us.csv")
    st.stop()

# --------------------------------------------------
# Selección de columnas
# --------------------------------------------------
num_cols = car_data.select_dtypes(include="number").columns.tolist()
all_cols = car_data.columns.tolist()

# --------------------------------------------------
# Histogramas
# --------------------------------------------------
st.subheader("📊 Histogramas")

hist_col = st.selectbox(
    "Selecciona una columna para el histograma",
    options=num_cols,
    index=num_cols.index("price") if "price" in num_cols else 0
)

if st.checkbox("Mostrar histograma"):
    fig = px.histogram(
        car_data,
        x=hist_col,
        title=f"Distribución de {hist_col}"
    )
    st.plotly_chart(fig, use_container_width=True)

# --------------------------------------------------
# Gráficos de dispersión
# --------------------------------------------------
st.subheader("📈 Gráficos de dispersión")

x_col = st.selectbox(
    "Eje X",
    options=all_cols,
    index=all_cols.index("odometer") if "odometer" in all_cols else 0
)

y_col = st.selectbox(
    "Eje Y",
    options=all_cols,
    index=all_cols.index("price") if "price" in all_cols else 0
)

color_col = st.selectbox(
    "Color (opcional)",
    options=[None] + all_cols,
    index=(all_cols.index("condition") + 1) if "condition" in all_cols else 0
)

if st.checkbox("Mostrar dispersión"):
    fig = px.scatter(
        car_data.dropna(subset=[x_col, y_col]),
        x=x_col,
        y=y_col,
        color=color_col,
        title=f"{y_col} vs {x_col}"
    )
    st.plotly_chart(fig, use_container_width=True)

# --------------------------------------------------
# Ejemplos rápidos (equivalentes a tus botones)
# --------------------------------------------------
st.subheader("⚡ Gráficos rápidos")

c1, c2, c3 = st.columns(3)

with c1:
    if st.button("Precio"):
        st.plotly_chart(px.histogram(car_data, x="price"), use_container_width=True)

with c2:
    if st.button("Kilometraje"):
        st.plotly_chart(px.histogram(car_data, x="odometer"), use_container_width=True)

with c3:
    if st.button("Año del modelo"):
        st.plotly_chart(px.histogram(car_data, x="model_year"), use_container_width=True)